### ISSUE TITLE
Unexpected behavior from $materialmap

### ISSUE THREAD

**Issue by Semx11** [Plancke/hypixel-php#20]
It shows 'GRILLED_PORK' instead of 'Gemini'. I checked the code at [Weapon.php](https://github.com/Plancke/hypixel-php/blob/master/Weapon.php) but everything seems fine.. but I'll let the pros fix that.

Here is an example of the incorrect image:
![image](https://cloud.githubusercontent.com/assets/7109469/9663099/127db4e2-5263-11e5-8a2f-11d6fdc46ba7.png)
Found at [/hypixel/weapons/MushCow](http://plancke.nl/hypixel/weapons/MushCow)
[Direct link to weapon](http://gen.plancke.nl/warlords/weapon/MushCow/1426374212074.png)

**Comment by Plancke** [comment]
Should be good now
