### ISSUE TITLE
With certain weapon names, the text does not fit in the border

### ISSUE THREAD

**Issue by Semx11** [Plancke/hypixel-php#22]
There are a few (at least one) combination of 'prefixes' and 'weapon skin names' that are too long and overflow the image border (at the weapon image generator)

The example I found was:
![image](https://cloud.githubusercontent.com/assets/7109469/9837743/8737f5d4-5a49-11e5-9db4-0709c73b5471.png)
[Direct link to weapon](http://gen.plancke.nl/warlords/weapon/Sitko73/1428323823018/0.png)

Possible fix 1: Variable width of image, depending on weapon name length (just like in MC).
Possible fix 2: Make all images wider, so the 'widest name' fits.

[end of report]-ish

**Comment by Plancke** [comment]
hmm, it should already calculate the correct width it needs

**Comment by Plancke** [comment]
Fixed
