### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by itsdezi** [Plancke/hypixel-php#37]
I have previously upload "hypixel-php/src/" to a webserver and HypixelPHP.php is returning nothing but a blank white page.

I'm stuck here, thank you for your help!

https://dezisrealm.tk/hpapi/HypixelPHP.php

https://dezisrealm.tk/phpversion.php

**Comment by Plancke** [comment]
The file itself won't do anything, you need to use the methods within it to start using it, there are some examples here: https://github.com/Plancke/hypixel-php/blob/old/HypixelPHP/examples/player.php

**Comment by itsdezi** [comment]
This was commented a while back, I ended up figuring out how make requests from the hypixel api, thank you
