### ISSUE TITLE
Update packagist

### ISSUE THREAD

**Issue by destruc7i0n** [Plancke/hypixel-php#38]
Maybe you should consider pushing new changes to packagist? It's been quite a while since you did, been needing to use

```
...
"repositories": [{
    "type": "git",
    "url": "http://github.com/Plancke/hypixel-php"
}],
"require": {
    "plancke/hypixel-php": "dev-master"
}
...
```

for a while now.

**Comment by Plancke** [comment]
Yeah I don't wanna just push new versions when all I did was change resources, it's a little too frequent.
