### ISSUE TITLE
plancke.io/hypixel/leaderboards/raw.php?type=guild.experience error 1020, blocked by cloudflare

### ISSUE THREAD

**Issue by Kuba314** [Plancke/hypixel-php#46]
It says "please enable cookies".​​​​

I use python3 aiohttp ClientSession with CookieJar (so cookies are enabled)(replicated with curl). I also tested that on another website, which said that cookies are working. I'm not abusing the link. I'm sending max. 1 request per hour.

I could not find any way to make my script run again. I tried just parsing the output of the lb page, but the thing is, there is only 25 visible entries. And to display more I'd have to use javascript. However, I can only send GET and POST requests.

How do I go about this?

PS: I know, that this may not be the best place to ask this question, but I can't message you through anything I tried (hypixel forums, twitter) and your website doesn't have an email address. If I can talk to you anywhere else, could you point me in the right direction?

**Comment by Plancke** [comment]
I added an ASN firewall to prevent bots from spam scraping my player pages instead of using an API key of themselves, added a bypass for the leaderboards endpoint. Might clean that up at some point and provide a "proper" API
