### ISSUE TITLE
Ratelimited?

### ISSUE THREAD

**Issue by GoogleSites** [Plancke/hypixel-php#52]
I have been using the `https://gen.plancke.io/exp/<username>.png` and `https://gen.plancke.io/achievementPoints/<username>.png` endpoints for a while with no problems. Now I receive a `403` error whenever I attempt to use them. Have I used them too much? Is there a way to appeal this or somehow receive access again?

**Comment by Plancke** [comment]
I implemented some rules on Cloudflare to protect my website, these should not affect normal visitors at all. What you're describing sounds a lot like bot traffic which I, unfortunately, can't directly support while ensuring decent performance for normal browser interactions. I'm continuously tweaking this as the attacks come in so I also can't guarantee if you find a workaround it won't also be abused by malicious users and subsequently blocked by me.
