### ISSUE TITLE
Guild rank not right

### ISSUE THREAD

**Issue by Macintosh-Fan** [Plancke/hypixel-php#55]
I have a guild that used to have an old rank (named `VIP`), but does not have that rank anymore and the user has a different rank.
![image](https://user-images.githubusercontent.com/50642934/118060810-7d87c880-b348-11eb-9acd-fbc9f1763ebf.png)

**Comment by Macintosh-Fan** [comment]
Maybe add a refresh button?

**Comment by Plancke** [comment]
fixed
