### ISSUE TITLE
link to SkyCrypt instead of sky.lea.moe on plancke.io

### ISSUE THREAD

**Issue by nstringham** [Plancke/hypixel-php#56]
### Proposal:
Currently `https://plancke.io/hypixel/player/stats/{username}` has a link called "SkyBlock Stats" that links to `https://sky.lea.moe/stats/{username}`. I would like to propose that this link should instead go to `https://sky.shiiyu.moe/stats/{username}`.

### Reasoning:
[sky.lea.moe](https://github.com/LeaPhant/skyblock-stats) is no longer maintained and recommends that its users use [SkyCrypt](https://github.com/SkyCryptWebsite/SkyCrypt) instead

**Comment by Plancke** [comment]
Changed, thank you
