### ISSUE TITLE
Old account with my username shows up when searched

### ISSUE THREAD

**Issue by Redie13** [Plancke/hypixel-php#67]
When I search for my account by name, Redie, what comes up is the person who had the username redie prior to me taking it. If I search by uuid then my account shows up like normal. I also can't keep the cycle going and search for my own old name because that has been taken by a different account, and when I search for my old name that other account shows up.
It's not a big issue just thought I'd mention it

**Comment by mdashlw** [comment]
Is this still an issue? Searching `Redie` right now returns stats for [`ddc317aaabfa4714b36127ec0155c44f`](https://namemc.com/profile/Redie.8) who has been the holder of this name since 2023

**Comment by Redie13** [comment]
oh yea true it works fine now. thx
